### ISSUE TITLE
ratelimit pypi issue

### ISSUE THREAD

**Issue by johnbumgarner** [deckar01/ratelimit#7]
I'm using deckar01-ratelimit in my open source project https://github.com/johnbumgarner/wordhoard.  My requirments.txt file is this:

```
backoff>=1.11.1
beautifulsoup4>=4.9.3
deckar01-ratelimit>=3.0.1
deepl>=1.1.2
lxml>=4.6.1
requests>=2.24.0
urllib3=1.25.11
```

My setup.py file has this:

```
install_requires=['backoff',
                      'bs4',
                      'deckar01-ratelimit',
                      'deepl',
                      'lxml',
                      'requests',
                      'urllib3']
```

Locally everything works fine, but when I push a package to PYPI something breaks, because I get this error:

```
from ratelimit import limits, RateLimitException
ModuleNotFoundError: No module named 'ratelimit'
```

I checked my packages and deckar01-ratelimit is installed.  If I install this package https://github.com/tomasbasham/ratelimit everything works.  

I only want the deckar01-ratelimit package.  How do I solve this issue?

**Comment by deckar01** [comment]
I am unable to reproduce that error. Installing `deckar01-ratelimit` in a fresh vdev and installing `wordhoard` in a fresh vdev both work as expected for me.

**Comment by johnbumgarner** [comment]
Version 1.4.9 of my app also had deckar01-ratelimit and it worked.  I wonder why a new development was required with 1.5.0.  PyCharm yells at me all the time that ratelimit isn't in the requirements file, but it it.  

Thanks for the help in solving this issue.
